name: suite2p
dependencies:
  - conda-forge::c-compiler
  - conda-forge::cxx-compiler
  - python>=3.7
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - h5py
  - scikit-image
  - scikit-learn
  - cython
  - conda-forge::opencv
  - ipyparallel
  - pyqt
  - pip:
    - git+https://github.com/flatironinstitute/CaImAn
    - pyqtgraph
    - natsort
    - scanimage-tiff-reader
    - rastermap==0.1.0
    - suite2p
    - cvxopt
    - git+https://github.com/losonczylab/sima
    - pyabf
    - tifffile
    - fbpca
    - tqdm
    - pynwb
    - holoviews
    - psutil
    - git+https://github.com/LelouchLamperougeVI/s2p-plugins.git
    - -e .
