name: suite2p
dependencies:
  - python>3.5
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - h5py
  - scikit-image
  - scikit-learn
  - cython
  - pip:
    - PyQt5
    - pyqtgraph
    - natsort
    - scanimage-tiff-reader
    - rastermap==0.1.0
    - cvxopt
    - git+https://github.com/losonczylab/sima
