name: suite2p
dependencies:
  - conda-forge::caiman
  - gcc_linux-64 # this issue is isolated to Arch Linux... the version of gcc is so new and amazing on this rolling release that ld doesn't understand what cython is outputting...
  - python>3.5
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - h5py
  - scikit-image
  - scikit-learn
  - cython
  - pip:
    - PyQt5
    - git+https://github.com/pyqtgraph/pyqtgraph
    - natsort
    - scanimage-tiff-reader
    - rastermap==0.1.0
    - suite2p
    - cvxopt
    - git+https://github.com/losonczylab/sima
    - pyabf
    - tifffile
    - fbpca
