name: suite2p
dependencies:
  - {{ compiler('c') }}
  - {{ compiler('c++') }}
  - gcc_linux-64 # this issue is isolated to Arch Linux... the version of gcc is so new and amazing on this rolling release that ld doesn't understand what cython is outputting...
  - gxx_linux-64
  - python>=3.7
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - h5py
  - scikit-image
  - scikit-learn
  - cython
  - conda-forge::opencv
  - ipyparallel
  - pyqt
  - pip:
    - git+https://github.com/flatironinstitute/CaImAn
    - PyQt5<5.12
    - pyqtgraph
    - natsort
    - scanimage-tiff-reader
    - rastermap==0.1.0
    - suite2p
    - cvxopt
    - git+https://github.com/losonczylab/sima
    - pyabf
    - tifffile
    - fbpca
    - tqdm
    - pynwb
    - holoviews
    - psutil
    - -e suite2p
